// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: msgs/msgs.proto

package go_msgs_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdJugador int32 `protobuf:"varint,1,opt,name=idJugador,proto3" json:"idJugador,omitempty"`
	Contenido int32 `protobuf:"varint,2,opt,name=contenido,proto3" json:"contenido,omitempty"`
}

func (x *Jugada) Reset() {
	*x = Jugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada) ProtoMessage() {}

func (x *Jugada) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada.ProtoReflect.Descriptor instead.
func (*Jugada) Descriptor() ([]byte, []int) {
	return file_msgs_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *Jugada) GetIdJugador() int32 {
	if x != nil {
		return x.IdJugador
	}
	return 0
}

func (x *Jugada) GetContenido() int32 {
	if x != nil {
		return x.Contenido
	}
	return 0
}

type Respuestalider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Siguejugando int32 `protobuf:"varint,1,opt,name=siguejugando,proto3" json:"siguejugando,omitempty"`
	Pasaronda    int32 `protobuf:"varint,2,opt,name=pasaronda,proto3" json:"pasaronda,omitempty"`
}

func (x *Respuestalider) Reset() {
	*x = Respuestalider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuestalider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuestalider) ProtoMessage() {}

func (x *Respuestalider) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuestalider.ProtoReflect.Descriptor instead.
func (*Respuestalider) Descriptor() ([]byte, []int) {
	return file_msgs_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *Respuestalider) GetSiguejugando() int32 {
	if x != nil {
		return x.Siguejugando
	}
	return 0
}

func (x *Respuestalider) GetPasaronda() int32 {
	if x != nil {
		return x.Pasaronda
	}
	return 0
}

type Peticion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreJugador string `protobuf:"bytes,1,opt,name=nombreJugador,proto3" json:"nombreJugador,omitempty"`
}

func (x *Peticion) Reset() {
	*x = Peticion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peticion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peticion) ProtoMessage() {}

func (x *Peticion) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peticion.ProtoReflect.Descriptor instead.
func (*Peticion) Descriptor() ([]byte, []int) {
	return file_msgs_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *Peticion) GetNombreJugador() string {
	if x != nil {
		return x.NombreJugador
	}
	return ""
}

type RespuestaPeticion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PuedeJugar int32 `protobuf:"varint,1,opt,name=puedeJugar,proto3" json:"puedeJugar,omitempty"`
	IdAsignado int32 `protobuf:"varint,2,opt,name=idAsignado,proto3" json:"idAsignado,omitempty"`
}

func (x *RespuestaPeticion) Reset() {
	*x = RespuestaPeticion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaPeticion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaPeticion) ProtoMessage() {}

func (x *RespuestaPeticion) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaPeticion.ProtoReflect.Descriptor instead.
func (*RespuestaPeticion) Descriptor() ([]byte, []int) {
	return file_msgs_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaPeticion) GetPuedeJugar() int32 {
	if x != nil {
		return x.PuedeJugar
	}
	return 0
}

func (x *RespuestaPeticion) GetIdAsignado() int32 {
	if x != nil {
		return x.IdAsignado
	}
	return 0
}

var File_msgs_msgs_proto protoreflect.FileDescriptor

var file_msgs_msgs_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x44, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x69, 0x64, 0x6f, 0x22, 0x52, 0x0a,
	0x0e, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x22, 0x0a, 0x0c, 0x73, 0x69, 0x67, 0x75, 0x65, 0x6a, 0x75, 0x67, 0x61, 0x6e, 0x64, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x75, 0x65, 0x6a, 0x75, 0x67, 0x61,
	0x6e, 0x64, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x61, 0x72, 0x6f, 0x6e, 0x64, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x73, 0x61, 0x72, 0x6f, 0x6e, 0x64,
	0x61, 0x22, 0x30, 0x0a, 0x08, 0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x22, 0x53, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x75, 0x65, 0x64,
	0x65, 0x4a, 0x75, 0x67, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x75,
	0x65, 0x64, 0x65, 0x4a, 0x75, 0x67, 0x61, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x41, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x64,
	0x41, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x32, 0x83, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x64,
	0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x0c,
	0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x0c, 0x2e, 0x6d,
	0x73, 0x67, 0x73, 0x2e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67,
	0x73, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x6c, 0x69, 0x64, 0x65, 0x72,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x4a, 0x75,
	0x67, 0x61, 0x72, 0x12, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x65, 0x74, 0x69, 0x63,
	0x69, 0x6f, 0x6e, 0x1a, 0x17, 0x2e, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x27,
	0x5a, 0x25, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f,
	0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgs_msgs_proto_rawDescOnce sync.Once
	file_msgs_msgs_proto_rawDescData = file_msgs_msgs_proto_rawDesc
)

func file_msgs_msgs_proto_rawDescGZIP() []byte {
	file_msgs_msgs_proto_rawDescOnce.Do(func() {
		file_msgs_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgs_msgs_proto_rawDescData)
	})
	return file_msgs_msgs_proto_rawDescData
}

var file_msgs_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msgs_msgs_proto_goTypes = []interface{}{
	(*Jugada)(nil),            // 0: msgs.jugada
	(*Respuestalider)(nil),    // 1: msgs.respuestalider
	(*Peticion)(nil),          // 2: msgs.Peticion
	(*RespuestaPeticion)(nil), // 3: msgs.RespuestaPeticion
}
var file_msgs_msgs_proto_depIdxs = []int32{
	0, // 0: msgs.LiderManagement.Enviarjugada:input_type -> msgs.jugada
	2, // 1: msgs.LiderManagement.PeticionJugar:input_type -> msgs.Peticion
	1, // 2: msgs.LiderManagement.Enviarjugada:output_type -> msgs.respuestalider
	3, // 3: msgs.LiderManagement.PeticionJugar:output_type -> msgs.RespuestaPeticion
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgs_msgs_proto_init() }
func file_msgs_msgs_proto_init() {
	if File_msgs_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgs_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgs_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuestalider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgs_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peticion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgs_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaPeticion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgs_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msgs_msgs_proto_goTypes,
		DependencyIndexes: file_msgs_msgs_proto_depIdxs,
		MessageInfos:      file_msgs_msgs_proto_msgTypes,
	}.Build()
	File_msgs_msgs_proto = out.File
	file_msgs_msgs_proto_rawDesc = nil
	file_msgs_msgs_proto_goTypes = nil
	file_msgs_msgs_proto_depIdxs = nil
}
